FROM node:16

# Working dir
ARG BANNERBEAR_API_KEY_WITHOUT_MAIN_IMAGES=${BANNERBEAR_API_KEY_WITHOUT_MAIN_IMAGES}
ARG BANNERBEAR_API_KEY_MAIN_IMAGES=${BANNERBEAR_API_KEY_MAIN_IMAGES}
ARG TWITTER_API_KEY=${TWITTER_API_KEY}
ARG TWITTER_API_SECRET=${TWITTER_API_SECRET}
ARG TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
ARG TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
ARG BEARER_TOKEN=${BEARER_TOKEN}
ARG  TWITTER_USER_ID=${TWITTER_USER_ID}
ARG CLOUDINARY_NAME=${CLOUDINARY_NAME}
ARG CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ARG CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ARG WOOCOMMERCE_WEBSITE=${WOOCOMMERCE_WEBSITE}
ARG WOOCOMMERC_CONSUMER_KEY=${WOOCOMMERC_CONSUMER_KEY}
ARG WOOCOMMERC_CONSUMER_SECRET=${WOOCOMMERC_CONSUMER_SECRET}
ARG ALLOWED_REQUESTS_PER_DAY=${ALLOWED_REQUESTS_PER_DAY}
ARG DATABASE_URL=${DATABASE_URL}
#ENV
ENV BANNERBEAR_API_KEY_WITHOUT_MAIN_IMAGES=${BANNERBEAR_API_KEY_WITHOUT_MAIN_IMAGES}
ENV BANNERBEAR_API_KEY_MAIN_IMAGES=${BANNERBEAR_API_KEY_MAIN_IMAGES}
ENV TWITTER_API_KEY=${TWITTER_API_KEY}
ENV TWITTER_API_SECRET=${TWITTER_API_SECRET}
ENV TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
ENV TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
ENV BEARER_TOKEN=${BEARER_TOKEN}
ENV TWITTER_USER_ID=${TWITTER_USER_ID}
ENV CLOUDINARY_NAME=${CLOUDINARY_NAME}
ENV CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
ENV CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
ENV WOOCOMMERCE_WEBSITE=${WOOCOMMERCE_WEBSITE}
ENV WOOCOMMERC_CONSUMER_KEY=${WOOCOMMERC_CONSUMER_KEY}
ENV WOOCOMMERC_CONSUMER_SECRET=${WOOCOMMERC_CONSUMER_SECRET}
ENV ALLOWED_REQUESTS_PER_DAY=${ALLOWED_REQUESTS_PER_DAY}
ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/app

COPY package*.json ./

RUN npm install

# Copy source files
COPY . .

RUN npx prisma generate

RUN npm run build

WORKDIR ./dist

CMD node index.js